---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: create ec2 instance
      ec2:
        region: us-east-1
        keypair: aws practice
        instance_type: t2.micro
        image: ami-1853ac65
        vpc_subnet_id: subnet-714fe15e
        assign_public_ip: yes
        wait: yes
        instance_tags:
           Name: "My-EC2"
      register: ec2

    - name: create dynamic hostgroup
      add_host: hostname={{ item.public_ip }} groups=ec2_server
      with_items: "{{ ec2.instances }}"
    - name: wait for the ec2 server ssh connection
      wait_for: host={{ item.public_ip }} port=22 state=started
      with_items: "{{ ec2.instances }}"
 
- hosts: ec2_server
  become: yes
  remote_user: ec2-user

  tasks:
    - name: install update
      command: sudo yum update -y 
    - name: install httpd server
      yum: name=httpd state=installed
    - name: start the httpd service
      service: name=httpd state=started
    - name: docker installation
      command: sudo yum install docker -y
    - name: starting of docker service
      command: service docker start
    - name: docker images
      command: docker pull centos:6.9
    - name: creating docker conatiner
      command: docker run -dti --name cnt1 centos:6.0

